CREATE TABLE site_content (
  `key` VARCHAR(100) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  body LONGTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
