/* ─────────────────────────────────────────────────────────────────
   UMRAH seed data — moved verbatim from react-app/src/data/umrah.ts.
   This is the source of truth the seeder loads into `umrah_packages`.
   After first seed, packages are managed in the admin panel / DB.

   ⚠️ DRAFT PLACEHOLDER CONTENT — REVIEW BEFORE PUBLISHING ⚠️
   The card-display fields below (name, tier, departureDates, roomRates,
   hotel ratings/distances, flight, inclusions, badge, mostPopular) and
   the AUD price labels were drafted as realistic placeholders and have
   NOT been verified against real fares, hotel facts, or flight schedules.
   Every value must be checked and corrected before going live.
   ───────────────────────────────────────────────────────────────── */

export type UmrahTier = "Economy" | "Premium" | "VIP";

export type UmrahRoomRate = {
  room: string; // "Quad" | "Triple" | "Double"
  priceDisplay: string; // per person, e.g. "A$1,875"
};

export type UmrahFlight = {
  airline: string; // e.g. "Qatar Airways"
  routing: string; // e.g. "1 stop via Doha"
};

/** Canonical inclusion keys — the Umrah page maps these to icon + label. */
export type UmrahInclusion =
  | "visa"
  | "flights"
  | "transfers"
  | "breakfast"
  | "ziyarah"
  | "guide";

export type UmrahPackage = {
  id: string;
  stars: string; // e.g. "5 Star", "4 & 5 Star", "5/4 Star"
  nights: string; // total, e.g. "10 nights"
  roomType: string; // base room share, e.g. "Quad"
  month: string; // e.g. "September"
  makkahHotel: string;
  makkahNights: string; // e.g. "6 nights"
  madinahHotel: string;
  madinahNights: string; // e.g. "4 nights"
  price: number; // numeric, for "from" + sorting
  priceDisplay: string; // e.g. "A$1,675" (AUD)
  /* ── Card-display fields (all optional — the page hides whatever is
     absent rather than rendering blanks). All DRAFT, see banner above. */
  name?: string; // display name, e.g. "10-Night Signature Umrah"
  tier?: UmrahTier;
  departureDates?: string[]; // e.g. ["5 Sep 2026", "19 Sep 2026"]
  roomRates?: UmrahRoomRate[]; // per-person rates by room share
  makkahRating?: number; // hotel stars, e.g. 5
  makkahDistance?: string; // e.g. "≈300 m from the Haram"
  madinahRating?: number;
  madinahDistance?: string; // e.g. "≈250 m from Masjid an-Nabawi"
  flight?: UmrahFlight;
  inclusions?: UmrahInclusion[];
  badge?: "Best Seller" | "Limited Seats" | "Early Bird";
  mostPopular?: boolean; // at most one per city — gets the highlighted card
};

export type UmrahCity = {
  id: string; // anchor slug, e.g. "perth"
  city: string; // departure city, e.g. "Perth"
  packages: UmrahPackage[];
};

export const UMRAH_CITIES: UmrahCity[] = [
  {
    id: "perth",
    city: "Perth",
    packages: [
      {
        id: "perth-1",
        stars: "5 Star",
        nights: "10 nights",
        roomType: "Quad",
        month: "September",
        makkahHotel: "Jabal Omar Marriott Hotel, Makkah",
        makkahNights: "6 nights",
        madinahHotel: "Pullman Zamzam Madina",
        madinahNights: "4 nights",
        price: 1675,
        priceDisplay: "A$1,675",
        name: "10-Night Signature Umrah",
        tier: "VIP",
        departureDates: ["4 Sep 2026", "18 Sep 2026"],
        roomRates: [
          { room: "Quad", priceDisplay: "A$1,675" },
          { room: "Triple", priceDisplay: "A$1,875" },
          { room: "Double", priceDisplay: "A$2,125" },
        ],
        makkahRating: 5,
        makkahDistance: "≈300 m from the Haram",
        madinahRating: 5,
        madinahDistance: "≈50 m from Masjid an-Nabawi",
        flight: { airline: "Qatar Airways", routing: "1 stop via Doha" },
        inclusions: [
          "visa",
          "flights",
          "transfers",
          "breakfast",
          "ziyarah",
          "guide",
        ],
      },
      {
        id: "perth-2",
        stars: "4 & 5 Star",
        nights: "7 nights",
        roomType: "Quad",
        month: "September",
        makkahHotel: "Makarem Ajyad Makkah Hotel",
        makkahNights: "4 nights",
        madinahHotel: "Saja Al Madinah Hotel 4*",
        madinahNights: "3 nights",
        price: 855,
        priceDisplay: "A$855",
        name: "7-Night Essential Umrah",
        tier: "Economy",
        departureDates: ["5 Sep 2026", "19 Sep 2026"],
        roomRates: [
          { room: "Quad", priceDisplay: "A$855" },
          { room: "Triple", priceDisplay: "A$960" },
          { room: "Double", priceDisplay: "A$1,085" },
        ],
        makkahRating: 4,
        makkahDistance: "≈150 m from the Haram",
        madinahRating: 4,
        madinahDistance: "≈250 m from Masjid an-Nabawi",
        flight: { airline: "Qatar Airways", routing: "1 stop via Doha" },
        inclusions: ["visa", "flights", "transfers", "breakfast"],
        badge: "Best Seller",
      },
      {
        id: "perth-3",
        stars: "4 Star",
        nights: "12 nights",
        roomType: "Quad",
        month: "September",
        makkahHotel: "Swissotel Al Maqam Makkah",
        makkahNights: "7 nights",
        madinahHotel: "Emaar Royal Hotel Al Madina",
        madinahNights: "5 nights",
        price: 1203,
        priceDisplay: "A$1,203",
        name: "12-Night Essential Umrah",
        tier: "Economy",
        departureDates: ["2 Sep 2026", "16 Sep 2026"],
        roomRates: [
          { room: "Quad", priceDisplay: "A$1,203" },
          { room: "Triple", priceDisplay: "A$1,345" },
          { room: "Double", priceDisplay: "A$1,530" },
        ],
        makkahRating: 5,
        makkahDistance: "≈100 m from the Haram",
        madinahRating: 5,
        madinahDistance: "≈200 m from Masjid an-Nabawi",
        flight: { airline: "Qatar Airways", routing: "1 stop via Doha" },
        inclusions: ["visa", "flights", "transfers", "breakfast"],
      },
      {
        id: "perth-4",
        stars: "5 Star",
        nights: "7 nights",
        roomType: "Quad",
        month: "September",
        makkahHotel: "Anjum Hotel 5*",
        makkahNights: "4 nights",
        madinahHotel: "Emaar Royal 5*",
        madinahNights: "3 nights",
        price: 1475,
        priceDisplay: "A$1,475",
        name: "7-Night Signature Umrah",
        tier: "VIP",
        departureDates: ["5 Sep 2026", "19 Sep 2026"],
        roomRates: [
          { room: "Quad", priceDisplay: "A$1,475" },
          { room: "Triple", priceDisplay: "A$1,650" },
          { room: "Double", priceDisplay: "A$1,875" },
        ],
        makkahRating: 5,
        makkahDistance: "≈450 m from the Haram",
        madinahRating: 5,
        madinahDistance: "≈200 m from Masjid an-Nabawi",
        flight: { airline: "Qatar Airways", routing: "1 stop via Doha" },
        inclusions: [
          "visa",
          "flights",
          "transfers",
          "breakfast",
          "ziyarah",
          "guide",
        ],
        badge: "Limited Seats",
      },
      {
        id: "perth-5",
        stars: "5/4 Star",
        nights: "10 nights",
        roomType: "Quad",
        month: "September",
        makkahHotel: "Swissotel al Maqam 5*",
        makkahNights: "6 nights",
        madinahHotel: "Saja Al Madinah 4*",
        madinahNights: "4 nights",
        price: 1524,
        priceDisplay: "A$1,524",
        name: "10-Night Select Umrah",
        tier: "Premium",
        departureDates: ["4 Sep 2026", "18 Sep 2026"],
        roomRates: [
          { room: "Quad", priceDisplay: "A$1,524" },
          { room: "Triple", priceDisplay: "A$1,705" },
          { room: "Double", priceDisplay: "A$1,935" },
        ],
        makkahRating: 5,
        makkahDistance: "≈100 m from the Haram",
        madinahRating: 4,
        madinahDistance: "≈250 m from Masjid an-Nabawi",
        flight: { airline: "Qatar Airways", routing: "1 stop via Doha" },
        inclusions: ["visa", "flights", "transfers", "breakfast", "ziyarah"],
        mostPopular: true,
      },
      {
        id: "perth-6",
        stars: "5/4 Star",
        nights: "12 nights",
        roomType: "Quad",
        month: "September",
        makkahHotel: "Swissotel al Maqam 5*",
        makkahNights: "6 nights",
        madinahHotel: "Taiba Madinah 5*",
        madinahNights: "6 nights",
        price: 1814,
        priceDisplay: "A$1,814",
        name: "12-Night Select Umrah",
        tier: "Premium",
        departureDates: ["2 Sep 2026", "16 Sep 2026"],
        roomRates: [
          { room: "Quad", priceDisplay: "A$1,814" },
          { room: "Triple", priceDisplay: "A$2,030" },
          { room: "Double", priceDisplay: "A$2,305" },
        ],
        makkahRating: 5,
        makkahDistance: "≈100 m from the Haram",
        madinahRating: 5,
        madinahDistance: "≈100 m from Masjid an-Nabawi",
        flight: { airline: "Qatar Airways", routing: "1 stop via Doha" },
        inclusions: ["visa", "flights", "transfers", "breakfast", "ziyarah"],
        badge: "Early Bird",
      },
    ],
  },
  {
    id: "melbourne",
    city: "Melbourne",
    packages: [
      {
        id: "melbourne-1",
        stars: "5 Star",
        nights: "7 nights",
        roomType: "Quad",
        month: "September",
        makkahHotel: "Anjum Hotel 5*",
        makkahNights: "4 nights",
        madinahHotel: "Emaar Royal 5*",
        madinahNights: "3 nights",
        price: 1509,
        priceDisplay: "A$1,509",
        name: "7-Night Signature Umrah",
        tier: "VIP",
        departureDates: ["5 Sep 2026", "19 Sep 2026"],
        roomRates: [
          { room: "Quad", priceDisplay: "A$1,509" },
          { room: "Triple", priceDisplay: "A$1,690" },
          { room: "Double", priceDisplay: "A$1,915" },
        ],
        makkahRating: 5,
        makkahDistance: "≈450 m from the Haram",
        madinahRating: 5,
        madinahDistance: "≈200 m from Masjid an-Nabawi",
        flight: { airline: "Emirates", routing: "1 stop via Dubai" },
        inclusions: [
          "visa",
          "flights",
          "transfers",
          "breakfast",
          "ziyarah",
          "guide",
        ],
        badge: "Limited Seats",
      },
      {
        id: "melbourne-2",
        stars: "5/4 Star",
        nights: "10 nights",
        roomType: "Quad",
        month: "September",
        makkahHotel: "Jabal Omar Marriott 5*",
        makkahNights: "6 nights",
        madinahHotel: "Saja al Madinah 4*",
        madinahNights: "4 nights",
        price: 1631,
        priceDisplay: "A$1,631",
        name: "10-Night Select Umrah",
        tier: "Premium",
        departureDates: ["4 Sep 2026", "18 Sep 2026"],
        roomRates: [
          { room: "Quad", priceDisplay: "A$1,631" },
          { room: "Triple", priceDisplay: "A$1,825" },
          { room: "Double", priceDisplay: "A$2,070" },
        ],
        makkahRating: 5,
        makkahDistance: "≈300 m from the Haram",
        madinahRating: 4,
        madinahDistance: "≈250 m from Masjid an-Nabawi",
        flight: { airline: "Emirates", routing: "1 stop via Dubai" },
        inclusions: ["visa", "flights", "transfers", "breakfast", "ziyarah"],
        mostPopular: true,
      },
      {
        id: "melbourne-3",
        stars: "5/4 Star",
        nights: "12 nights",
        roomType: "Quad",
        month: "September",
        makkahHotel: "Anjum Hotel 5*",
        makkahNights: "6 nights",
        madinahHotel: "Saja al Madinah 4*",
        madinahNights: "6 nights",
        price: 1719,
        priceDisplay: "A$1,719",
        name: "12-Night Select Umrah",
        tier: "Premium",
        departureDates: ["2 Sep 2026", "16 Sep 2026"],
        roomRates: [
          { room: "Quad", priceDisplay: "A$1,719" },
          { room: "Triple", priceDisplay: "A$1,925" },
          { room: "Double", priceDisplay: "A$2,185" },
        ],
        makkahRating: 5,
        makkahDistance: "≈450 m from the Haram",
        madinahRating: 4,
        madinahDistance: "≈250 m from Masjid an-Nabawi",
        flight: { airline: "Emirates", routing: "1 stop via Dubai" },
        inclusions: ["visa", "flights", "transfers", "breakfast", "ziyarah"],
        badge: "Early Bird",
      },
    ],
  },
  {
    id: "sydney",
    city: "Sydney",
    packages: [
      {
        id: "sydney-1",
        stars: "5 Star",
        nights: "7 nights",
        roomType: "Quad",
        month: "September",
        makkahHotel: "Anjum Hotel 5*",
        makkahNights: "4 nights",
        madinahHotel: "Pullman ZamZam Medina 5*",
        madinahNights: "3 nights",
        price: 1492,
        priceDisplay: "A$1,492",
        name: "7-Night Signature Umrah",
        tier: "VIP",
        departureDates: ["5 Sep 2026", "19 Sep 2026"],
        roomRates: [
          { room: "Quad", priceDisplay: "A$1,492" },
          { room: "Triple", priceDisplay: "A$1,670" },
          { room: "Double", priceDisplay: "A$1,895" },
        ],
        makkahRating: 5,
        makkahDistance: "≈450 m from the Haram",
        madinahRating: 5,
        madinahDistance: "≈50 m from Masjid an-Nabawi",
        flight: { airline: "Etihad Airways", routing: "1 stop via Abu Dhabi" },
        inclusions: [
          "visa",
          "flights",
          "transfers",
          "breakfast",
          "ziyarah",
          "guide",
        ],
        badge: "Limited Seats",
      },
      {
        id: "sydney-2",
        stars: "5/4 Star",
        nights: "10 nights",
        roomType: "Quad",
        month: "September",
        makkahHotel: "Jabal Omar Marriott 5*",
        makkahNights: "6 nights",
        madinahHotel: "Saja Al Madinah 4*",
        madinahNights: "4 nights",
        price: 1615,
        priceDisplay: "A$1,615",
        name: "10-Night Select Umrah",
        tier: "Premium",
        departureDates: ["4 Sep 2026", "18 Sep 2026"],
        roomRates: [
          { room: "Quad", priceDisplay: "A$1,615" },
          { room: "Triple", priceDisplay: "A$1,810" },
          { room: "Double", priceDisplay: "A$2,050" },
        ],
        makkahRating: 5,
        makkahDistance: "≈300 m from the Haram",
        madinahRating: 4,
        madinahDistance: "≈250 m from Masjid an-Nabawi",
        flight: { airline: "Etihad Airways", routing: "1 stop via Abu Dhabi" },
        inclusions: ["visa", "flights", "transfers", "breakfast", "ziyarah"],
        mostPopular: true,
      },
      {
        id: "sydney-3",
        stars: "5/4 Star",
        nights: "12 nights",
        roomType: "Quad",
        month: "September",
        makkahHotel: "Swissotel al Maqam 5*",
        makkahNights: "6 nights",
        madinahHotel: "Saja Al Madinah 4*",
        madinahNights: "6 nights",
        price: 1778,
        priceDisplay: "A$1,778",
        name: "12-Night Select Umrah",
        tier: "Premium",
        departureDates: ["2 Sep 2026", "16 Sep 2026"],
        roomRates: [
          { room: "Quad", priceDisplay: "A$1,778" },
          { room: "Triple", priceDisplay: "A$1,990" },
          { room: "Double", priceDisplay: "A$2,260" },
        ],
        makkahRating: 5,
        makkahDistance: "≈100 m from the Haram",
        madinahRating: 4,
        madinahDistance: "≈250 m from Masjid an-Nabawi",
        flight: { airline: "Etihad Airways", routing: "1 stop via Abu Dhabi" },
        inclusions: ["visa", "flights", "transfers", "breakfast", "ziyarah"],
        badge: "Early Bird",
      },
    ],
  },
  {
    id: "brisbane",
    city: "Brisbane",
    packages: [
      {
        id: "brisbane-1",
        stars: "5 Star",
        nights: "10 nights",
        roomType: "Quad",
        month: "October",
        makkahHotel: "Conrad Makkah",
        makkahNights: "6 nights",
        madinahHotel: "The Oberoi Madinah",
        madinahNights: "4 nights",
        price: 1720,
        priceDisplay: "A$1,720",
        name: "10-Night Signature Umrah",
        tier: "VIP",
        departureDates: ["3 Oct 2026", "17 Oct 2026"],
        roomRates: [
          { room: "Quad", priceDisplay: "A$1,720" },
          { room: "Triple", priceDisplay: "A$1,930" },
          { room: "Double", priceDisplay: "A$2,190" },
        ],
        makkahRating: 5,
        makkahDistance: "≈200 m from the Haram",
        madinahRating: 5,
        madinahDistance: "≈80 m from Masjid an-Nabawi",
        flight: { airline: "Singapore Airlines", routing: "1 stop via Singapore" },
        inclusions: [
          "visa",
          "flights",
          "transfers",
          "breakfast",
          "ziyarah",
          "guide",
        ],
        badge: "Best Seller",
        mostPopular: true,
      },
      {
        id: "brisbane-2",
        stars: "4 Star",
        nights: "9 nights",
        roomType: "Quad",
        month: "October",
        makkahHotel: "Makkah Towers",
        makkahNights: "5 nights",
        madinahHotel: "Al Eiman Royal Hotel",
        madinahNights: "4 nights",
        price: 1190,
        priceDisplay: "A$1,190",
        name: "9-Night Select Umrah",
        tier: "Premium",
        departureDates: ["10 Oct 2026", "24 Oct 2026"],
        roomRates: [
          { room: "Quad", priceDisplay: "A$1,190" },
          { room: "Triple", priceDisplay: "A$1,330" },
          { room: "Double", priceDisplay: "A$1,510" },
        ],
        makkahRating: 4,
        makkahDistance: "≈400 m from the Haram",
        madinahRating: 4,
        madinahDistance: "≈300 m from Masjid an-Nabawi",
        flight: { airline: "Singapore Airlines", routing: "1 stop via Singapore" },
        inclusions: ["visa", "flights", "transfers", "breakfast"],
      },
      {
        id: "brisbane-3",
        stars: "3 Star",
        nights: "7 nights",
        roomType: "Quad",
        month: "October",
        makkahHotel: "Al Kiswah Towers Hotel",
        makkahNights: "4 nights",
        madinahHotel: "Diyar International Hotel",
        madinahNights: "3 nights",
        price: 845,
        priceDisplay: "A$845",
        name: "7-Night Value Umrah",
        tier: "Economy",
        departureDates: ["12 Oct 2026", "26 Oct 2026"],
        roomRates: [
          { room: "Quad", priceDisplay: "A$845" },
          { room: "Triple", priceDisplay: "A$950" },
          { room: "Double", priceDisplay: "A$1,075" },
        ],
        makkahRating: 3,
        makkahDistance: "≈900 m from the Haram (shuttle provided)",
        madinahRating: 3,
        madinahDistance: "≈600 m from Masjid an-Nabawi",
        flight: { airline: "Singapore Airlines", routing: "1 stop via Singapore" },
        inclusions: ["visa", "flights", "transfers"],
        badge: "Limited Seats",
      },
    ],
  },
  {
    id: "adelaide",
    city: "Adelaide",
    packages: [
      {
        id: "adelaide-1",
        stars: "5 Star",
        nights: "12 nights",
        roomType: "Quad",
        month: "November",
        makkahHotel: "Raffles Makkah Palace",
        makkahNights: "7 nights",
        madinahHotel: "Anwar Al Madinah Mövenpick",
        madinahNights: "5 nights",
        price: 1980,
        priceDisplay: "A$1,980",
        name: "12-Night Signature Umrah",
        tier: "VIP",
        departureDates: ["7 Nov 2026", "21 Nov 2026"],
        roomRates: [
          { room: "Quad", priceDisplay: "A$1,980" },
          { room: "Triple", priceDisplay: "A$2,220" },
          { room: "Double", priceDisplay: "A$2,520" },
        ],
        makkahRating: 5,
        makkahDistance: "≈150 m from the Haram",
        madinahRating: 5,
        madinahDistance: "≈120 m from Masjid an-Nabawi",
        flight: { airline: "Emirates", routing: "1 stop via Dubai" },
        inclusions: [
          "visa",
          "flights",
          "transfers",
          "breakfast",
          "ziyarah",
          "guide",
        ],
      },
      {
        id: "adelaide-2",
        stars: "4 Star",
        nights: "10 nights",
        roomType: "Quad",
        month: "November",
        makkahHotel: "Makkah Clock Royal Tower foothills",
        makkahNights: "6 nights",
        madinahHotel: "Dallah Taibah Hotel",
        madinahNights: "4 nights",
        price: 1320,
        priceDisplay: "A$1,320",
        name: "10-Night Select Umrah",
        tier: "Premium",
        departureDates: ["9 Nov 2026", "23 Nov 2026"],
        roomRates: [
          { room: "Quad", priceDisplay: "A$1,320" },
          { room: "Triple", priceDisplay: "A$1,475" },
          { room: "Double", priceDisplay: "A$1,680" },
        ],
        makkahRating: 4,
        makkahDistance: "≈350 m from the Haram",
        madinahRating: 4,
        madinahDistance: "≈280 m from Masjid an-Nabawi",
        flight: { airline: "Emirates", routing: "1 stop via Dubai" },
        inclusions: ["visa", "flights", "transfers", "breakfast", "ziyarah"],
        badge: "Best Seller",
      },
      {
        id: "adelaide-3",
        stars: "3 Star",
        nights: "8 nights",
        roomType: "Quad",
        month: "November",
        makkahHotel: "Rawasi Al Bait Hotel",
        makkahNights: "5 nights",
        madinahHotel: "Saraya Taba Hotel",
        madinahNights: "3 nights",
        price: 910,
        priceDisplay: "A$910",
        name: "8-Night Value Umrah",
        tier: "Economy",
        departureDates: ["11 Nov 2026", "25 Nov 2026"],
        roomRates: [
          { room: "Quad", priceDisplay: "A$910" },
          { room: "Triple", priceDisplay: "A$1,020" },
          { room: "Double", priceDisplay: "A$1,160" },
        ],
        makkahRating: 3,
        makkahDistance: "≈1 km from the Haram (shuttle provided)",
        madinahRating: 3,
        madinahDistance: "≈550 m from Masjid an-Nabawi",
        flight: { airline: "Emirates", routing: "1 stop via Dubai" },
        inclusions: ["visa", "flights", "transfers"],
      },
    ],
  },
];
